name: CI

on:
  pull_request:
    branches: [dev]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: yarn install
        uses: borales/actions-yarn@v2.3.0
        with: 
          cmd: install --frozen-lockfile

      - name: yarn build
        uses: borales/actions-yarn@v2.3.0
        with: 
          cmd: build