name: CI

on:
  pull_request:
    branches: [dev]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: yarn install
        uses: borales/actions-yarn@v2.0.0
        with: install

      - name: yarn build
        uses: borales/actions-yarn@v2.0.0
        with: build